import {
  Dumbbell,
  Briefcase,
  BookOpen,
  Target,
  FlaskConical,
  Code2,
  PenTool,
  Palette,
  Film,
  Music,
  HeartHandshake,
  Landmark,
  Plane,
  Home,
  Sprout,
  Wrench,
  Calculator,
  Calendar,
  Lightbulb,
  Folder,
  GraduationCap,
  BookA,
  Flag,
  Tv,
  TvMinimalPlay,
  Beef,
  Heart,
  Mails,
  Pencil,
  Laptop,
} from "lucide-react";

export const COLOR_PALETTES = [
  { id: "indigo", primary: "#5C6BC0", soft: "#E3E6FB", name: "Индиго" },
  { id: "green", primary: "#52B33D", soft: "#CFF6D4", name: "Зеленый" },
  { id: "orange", primary: "#E8A933", soft: "#FFE4BE", name: "Оранжевый" },
  { id: "blue", primary: "#3A8DFF", soft: "#D0E6FF", name: "Синий" },
  { id: "red", primary: "#E14A4A", soft: "#FFD6D6", name: "Красный" },
  { id: "pink", primary: "#D85BA1", soft: "#FFE1F1", name: "Розовый" },
  { id: "teal", primary: "#2DB5A7", soft: "#C6F1EC", name: "Бирюзовый" },
  { id: "purple", primary: "#916DFF", soft: "#DBD2FF", name: "Фиолетовый" },
  { id: "gray", primary: "#6B7280", soft: "#E5E7EB", name: "Серый" },
];

export const ICONS = [
  { id: "folder", icon: Folder, name: "Папка" },
  { id: "briefcase", icon: Briefcase, name: "Портфель" },
  { id: "book-open", icon: BookOpen, name: "Книга" },
  { id: "book-a", icon: BookA, name: "Книга 2" },
  { id: "graduation-cap", icon: GraduationCap, name: "Учеба" },
  { id: "pencil", icon: Pencil, name: "Карандаш" },
  { id: "laptop", icon: Laptop, name: "Ноутбук" },
  { id: "flag", icon: Flag, name: "Флаг" },
  { id: "flask-conical", icon: FlaskConical, name: "Эксперимент" },
  { id: "code-2", icon: Code2, name: "Код" },
  { id: "palette", icon: Palette, name: "Арт" },
  { id: "tv", icon: TvMinimalPlay, name: "Телевидение" },
  { id: "heart", icon: Heart, name: "Отношения" },
  { id: "heart-handshake", icon: HeartHandshake, name: "Волонтерство" },
  { id: "mails", icon: Mails, name: "Почта" },
  { id: "plane", icon: Plane, name: "Путешествия" },
  { id: "home", icon: Home, name: "Дом" },
  { id: "beef", icon: Beef, name: "Мясо" },
  { id: "sprout", icon: Sprout, name: "Новый проект" },
  { id: "wrench", icon: Wrench, name: "Ремонт" },
  { id: "calculator", icon: Calculator, name: "Калькулятор" },
  { id: "calendar", icon: Calendar, name: "Календарь" },
  { id: "lightbulb", icon: Lightbulb, name: "Идеи" },
  { id: "dumbbell", icon: Dumbbell, name: "Гантель" },
];
