import {
  Dumbbell,
  Briefcase,
  BookOpen,
  FlaskConical,
  Code2,
  Palette,
  HeartHandshake,
  Plane,
  Home,
  Sprout,
  Wrench,
  Calculator,
  Calendar,
  Lightbulb,
  Folder,
  GraduationCap,
  BookA,
  Flag,
  TvMinimalPlay,
  Beef,
  Heart,
  Mails,
  Pencil,
  Laptop,
} from "lucide-react";

export const COLOR_PALETTES = [
  { id: "indigo", primary: "#5C6BC0", soft: "#E3E6FB" },
  { id: "green", primary: "#52B33D", soft: "#CFF6D4" },
  { id: "orange", primary: "#E8A933", soft: "#FFE4BE" },
  { id: "blue", primary: "#3A8DFF", soft: "#D0E6FF" },
  { id: "red", primary: "#E14A4A", soft: "#FFD6D6" },
  { id: "pink", primary: "#D85BA1", soft: "#FFE1F1" },
  { id: "teal", primary: "#2DB5A7", soft: "#C6F1EC" },
  { id: "purple", primary: "#916DFF", soft: "#DBD2FF" },
  { id: "gray", primary: "#6B7280", soft: "#E5E7EB" },
];

export const ICONS = [
  { id: "folder", icon: Folder },
  { id: "briefcase", icon: Briefcase },
  { id: "book-open", icon: BookOpen },
  { id: "book-a", icon: BookA },
  { id: "graduation-cap", icon: GraduationCap },
  { id: "pencil", icon: Pencil },
  { id: "laptop", icon: Laptop },
  { id: "flag", icon: Flag },
  { id: "flask-conical", icon: FlaskConical },
  { id: "code-2", icon: Code2 },
  { id: "palette", icon: Palette },
  { id: "tv", icon: TvMinimalPlay },
  { id: "heart", icon: Heart },
  { id: "heart-handshake", icon: HeartHandshake },
  { id: "mails", icon: Mails },
  { id: "plane", icon: Plane },
  { id: "home", icon: Home },
  { id: "beef", icon: Beef },
  { id: "sprout", icon: Sprout },
  { id: "wrench", icon: Wrench },
  { id: "calculator", icon: Calculator },
  { id: "calendar", icon: Calendar },
  { id: "lightbulb", icon: Lightbulb },
  { id: "dumbbell", icon: Dumbbell },
];
